version: 0.2

phases:
  install:
    commands:
      - cd source/code/
      - echo "Installing dependencies - `pwd`"
      - pip install pytz
      - pytz_location=$(pip show pytz | grep Location | cut -d':' -f 2 | tr -d " ")
      - cp -r ${pytz_location}/pytz .
      - echo "Installing dependencies completed `date`"
  pre_build:
    commands:
      - cd deployment/
      - echo "Executing unit tests - `pwd`"
      - if [ -f ./run-unit-tests.sh ]; then chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh; fi
      - echo "Executing unit tests completed `date`"
  build:
    commands:
      - cd source/code/
      - echo "Starting build `date` in `pwd`"
      - chmod +x ../../deployment/build-s3-dist.sh && source ../../deployment/build-s3-dist.sh ${bucket} ${solution} ${version} ${region}
      - echo "Build completed `date`"
  post_build:
    commands:
      - cd source/code/
      - echo "Upload the artifacts to S3 `date` in `pwd`"
      - echo "Run s3api put-public-access-block"
      - aws s3api put-public-access-block --bucket ${bucket} \
        --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true" --region ${region}
      - echo "Uploading the artifacts"
      - chmod +x ../../deployment/deploy-dist.sh && source ../../deployment/deploy-dist.sh ${bucket} ${solution} ${version} ${region}
      - "echo cleanup pytz/"
      - rm -r pytz/
      - echo "Post build completed on `date`"

artifacts:
  files:
      - deployment/**/*
      - CHANGELOG.md
      - buildspec.yml